services:

  # the first service postgreSQL
  pgdatabase:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - /home/filo/works/data-engineering-zoomcamp/ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  # the second service pgadmin to explor the database
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  # the third python service to upload data into the database service
  data_uploader:
    build: 
      context: .
      dockerfile: uploader
    volumes:
      - /home/filo/works/data-engineering-zoomcamp:/app
    depends_on:
      - pgdatabase  
    command: ["python", "upload-data.py"]
